# Generated by Django 5.1.3 on 2024-12-08 14:12

import django.core.validators
import test_app.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_bio_alter_profile_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=80, null=True, validators=[django.core.validators.MaxLengthValidator(80), test_app.users.validators.first_name_validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=80, null=True, validators=[django.core.validators.MaxLengthValidator(80), test_app.users.validators.last_name_validate_only_letters]),
        ),
    ]
