# Generated by Django 5.1.3 on 2024-12-18 13:53

import test_app.blog.validators
import test_app.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=100, null=True, validators=[test_app.users.validators.validate_socials_url]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=100, null=True, validators=[test_app.users.validators.validate_socials_url]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/', validators=[test_app.blog.validators.validate_image_file]),
        ),
    ]
