# Generated by Django 5.1.3 on 2024-11-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_category_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='type_of_plant',
            field=models.CharField(choices=[('Flower', 'Flower'), ('Cactus', 'Cactus'), ('Herb', 'Herb'), ('Tree', 'Tree'), ('Bush', 'Bush')], default='Flower'),
        ),
    ]
