# Generated by Django 5.1.3 on 2024-11-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
