# Generated by Django 5.1.3 on 2024-12-08 14:16

import test_app.blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='habitat',
            field=models.CharField(max_length=100, validators=[test_app.blog.validators.plant_habitat_validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=35, validators=[test_app.blog.validators.title_validate_only_letters]),
        ),
    ]
