# Generated by Django 5.1.3 on 2024-12-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='wikipedia_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
