# Generated by Django 5.1.3 on 2024-12-18 13:47

import test_app.blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_plant_wikipedia_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/plants/', validators=[test_app.blog.validators.validate_image_file]),
        ),
    ]
