# Generated by Django 5.1.3 on 2024-12-18 13:50

import test_app.blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(default='Plant', max_length=100, validators=[test_app.blog.validators.title_validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='wikipedia_url',
            field=models.URLField(blank=True, null=True, validators=[test_app.blog.validators.validate_wikipedia_url]),
        ),
    ]
