"""
Django settings for test_app project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import dj_database_url
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-vw_!ragq0hr@^vv2tqcrd*(97ney9$+aocswy%t3w8gz)!6*e$'
SECRET_KEY = os.environ.get('SECRET_KEY')
# SECRET_KEY = "b13ffe9ba7abd3b202c0868f75100e88"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'



STATIC_URL = '/static/'  # URL to access static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Deployment directory
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Local static file directories
#
# ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
#ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split()
ALLOWED_HOSTS = ['127.0.0.1', 'plantheaven.onrender.com', 'localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "test_app.blog",
    "test_app.common",
    "test_app.users",
]

MIDDLEWARE = [

    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
ROOT_URLCONF = 'test_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'test_app/../templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'test_app.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'green_forum_database',
#         'USER': 'postgres',
#         'PASSWORD': '1',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#     }
# }
# INTERNAL DATEBASE URL: dpg-cthg4b23esus73b612ng-a
# EXTERNAL DATEBASE URL: dpg-cthg4b23esus73b612ng-a.oregon-postgres.render.com
database_host = os.environ.get('DATABASE_URL', '')
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'green_forum_database',
        'USER': 'green_forum_database_user',
        'PASSWORD': 'ry3zSAfatjWapFjQoR6MNZQlOcVQwFgM',
        'HOST': database_host,
        'PORT': '5432',
    }
}
#database_url = os.environ.get('DATABASE_URL', '')
# DATABASES['default'] = dj_database_url.parse("postgresql://green_forum_database_user:ry3zSAfatjWapFjQoR6MNZQlOcVQwFgM@dpg-cthg4b23esus73b612ng-a/green_forum_database")
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#STATIC_URL = 'static/'
#STATICFILES_DIRS = (
#    BASE_DIR / 'static/',
#)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
